@startuml
title ChambeApp - Billetera Virtual y Monedas
skinparam componentStyle rectangle
actor PDS
actor Solicitante
[Wallet] as W
[Monedas] as M
[Transaccion] as T
[Pasarela Pago] as P
PDS --> W : recibe saldo
Solicitante --> P : paga
P --> W : descuenta comision
W --> M : usa monedas (modalidad B)
W --> T : registra historial
@enduml
